import XCTest
@testable import PostMDCore

/// Cross-component round trip: read fixtures/roundtrip.json (machine-generated by the extension
/// encoder) as-is, and check that the real app parser restores each encoded value back to its
/// original input. Matching test on the extension side: extension/test/crosscomponent.test.ts
/// (verifies the same file through the encoder). Since both components share one machine-generated
/// source, there is no risk of both passing the same hand-typed wrong vector.
final class CrossComponentTests: XCTestCase {
    private struct Fixture: Decodable { let input: String; let encoded: String; let note: String? }
    private struct Root: Decodable { let fixtures: [Fixture] }

    private func loadFixtures() throws -> [Fixture] {
        // Locate the shared fixtures at the repo root relative to this source file
        // (independent of cwd or build directory).
        // .../app/Tests/PostMDTests/CrossComponentTests.swift → 4 levels up = repo root
        var root = URL(fileURLWithPath: #filePath)
        for _ in 0..<4 { root.deleteLastPathComponent() }
        let url = root.appendingPathComponent("fixtures/roundtrip.json")
        let data = try Data(contentsOf: url)
        return try JSONDecoder().decode(Root.self, from: data).fixtures
    }

    func testFixturesRoundTripThroughParser() throws {
        let fixtures = try loadFixtures()
        XCTAssertFalse(fixtures.isEmpty, "fixture load failed / empty array — path regression guard")

        for fx in fixtures {
            let url = try XCTUnwrap(
                URL(string: "post-md://new?content=\(fx.encoded)"),
                "URL build failed: \(fx.encoded)")
            let result = StickyURLParser.parse(url)
            XCTAssertEqual(
                result, .success(.new(content: fx.input)),
                "parser did not restore the original (\(fx.note ?? fx.input)) — encoded=\(fx.encoded)")
        }
    }
}
